services:
  selenium-hub:
    image: selenium/hub:4.21.0
    platform: linux/amd64
    ports:
      - "4444:4444"

  chrome-node:
    image: selenium/node-chrome:4.21.0
    platform: linux/amd64
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3   
    shm_size: 2gb