name: Run Tests

on:
  workflow_dispatch:
    inputs:
      testType:
        description: "Select test category"
        required: true
        default: all
        type: choice
        options:
          - all
          - smoke-sanity
          - regression
          - api

jobs:

  run-tests:
    runs-on: ubuntu-latest

    env:
      CI: true
      BROWSER: chrome

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - run: dotnet restore
      - run: dotnet build --no-restore

      - name: Run Selected Tests
        run: |
          if [ "${{ github.event.inputs.testType }}" = "smoke-sanity" ]; then
            dotnet test --no-build --filter "Category=smoke|Category=sanity"

          elif [ "${{ github.event.inputs.testType }}" = "regression" ]; then
            dotnet test --no-build --filter "Category=regression"

          elif [ "${{ github.event.inputs.testType }}" = "api" ]; then
            dotnet test --no-build --filter "Category=api"

          elif [ "${{ github.event.inputs.testType }}" = "all" ]; then
            dotnet test --no-build
          fi
